--[ CONEXÃO BANCO ]----------------------------------------------------------------------------------------------------------------------------
vRP.prepare("vrp_pass/get_coins", "SELECT vip FROM sjr_box WHERE user_id = @user_id")
vRP.prepare("vrp_pass/get_all_users", "SELECT id FROM characters")
vRP.prepare("vrp_pass/get_savings", "SELECT poupanca FROM characters WHERE id = @user_id")
vRP.prepare("vrp_pass/get_transacoes", "SELECT * FROM require_bank_historico WHERE user_id = @user_id ORDER BY date DESC LIMIT 17")
vRP.prepare("vrp_pass/set_poupanca","UPDATE characters SET poupanca = @poupanca WHERE id = @user_id")
vRP.prepare("vrp_pass/set_bank","UPDATE characters SET banco = @banco WHERE id = @user_id")
vRP.prepare("vrp_pass/add_historico","INSERT INTO require_bank_historico(user_id, type, amount, date) VALUES(@user_id, @type, @amount, NOW())")
vRP.prepare("vrp_pass/get_pix", "SELECT * FROM characters WHERE chavePix = @chavePix")
vRP.prepare("vrp_pass/get_pix_user", "SELECT chavePix FROM characters WHERE id = @user_id")
vRP.prepare("vrp_pass/get_photo", "SELECT avatarURL FROM smartphone_instagram WHERE id = @user_id")
vRP.prepare("vrp_pass/set_pix","UPDATE characters SET chavePix = @chavePix WHERE id = @user_id")
vRP.prepare("vrp_pass/update_savings", "UPDATE characters SET poupanca = @poupanca WHERE id = @user_id")
vRP.prepare("vrp_pass/get_status_cartao", "SELECT status FROM require_bank_login WHERE user_id = @user_id")
vRP.prepare("vrp_pass/up_status_cartao", "UPDATE require_bank_login SET status = @status WHERE user_id = @user_id")
vRP.prepare("vrp_pass/insert_conta", "INSERT INTO require_bank_login(user_id, login, senha) VALUES(@user_id, @login, @senha)")
vRP.prepare("vrp_pass/update_conta", "UPDATE require_bank_login SET login = @login, senha = @senha WHERE user_id = @user_id")
vRP.prepare("vrp_pass/get_conta", "SELECT * FROM require_bank_login WHERE login = @login AND senha = @senha")